version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Api/Dockerfile
    image: hotwingsapi
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: HotWingsDB
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "8080:80"
    depends_on:
      - db

  migrate:
    build:
      context: .
      dockerfile: Api/Dockerfile.migrations
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - db

volumes:
  db_data:
